Fix unit tests
NatLabRockies/ComStock pull request #137
Opened 2024-03-08 17:29 UTC by mdahlhausen

Pull request overview
---------------------

A combination of several unit test fixes to pass the CI.

### Pull Request Author

This pull request makes changes to (select all the apply):
 - [ ] Documentation
 - [ ] Infrastructure (includes singularity image, buildstock batch, dependencies, continuous integration tests)
 - [ ] Sampling
 - [x] Workflow Measures
 - [x] Upgrade Measures
 - [ ] Reporting Measures
 - [ ] Postprocessing

Author pull request checklist:
 - [x] Tagged the pull request with the appropriate label (documentation, infrastructure, sampling, workflow measure, upgrade measure, reporting measure, postprocessing) to help categorize changes in the release notes.
 - [ ] Added tests for new measures
 - [x] Updated measure .xml(s)
 - [ ] Register values added to `comstock_column_definitions.csv`
 - [ ] Both `options_lookup.tsv` files updated
 - [ ] 10k+ test run
 - [ ] Change documentation written
 - [ ] Measure documentation written
 - [ ] ComStock documentation updated
 - [ ] Changes reflected in example `.yml` files
 - [ ] Changes reflected in `README.md` files
 - [ ] Added 'See ComStock License' language to first two lines of each code file
 - [ ] Implements corresponding measure tests and indexing path in `test/measure_tests.txt` or/and `test/resource_measure_tests.txt`
 - [ ] All new and existing tests pass the CI

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a code review on GitHub
 - [ ] All related changes have been implemented: data and method additions, changes, tests
 - [ ] If fixing a defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] Reviewed change documentation
 - [ ] Ensured code files contain License reference
 - [ ] Results differences are reasonable
 - [ ] Make sure the newly added measures has been added with tests and indexed properly
 - [ ] CI status: all tests pass

#### ComStock Licensing Language - Add to Beginning of Each Code File
```
# ComStock™, Copyright (c) 2023 Alliance for Sustainable Energy, LLC. All rights reserved.
# See top level LICENSE.txt file for license terms.
```

2024-03-11 15:00 UTC, eringold requested changes
Remove la_100_qaqc from https://github.com/NREL/ComStock/blob/main/ymls/bsb-integration-test-baseline.yml to prevent buildstock_local test failure

2024-03-11 16:34 UTC, mdahlhausen commented
@eringold removed that line from the .yml

2024-03-11 17:38 UTC, eringold commented
@mpraprost I see one error still on `create_typical_building_from_model_test.rb`: 
```
  1) Error:
CreateTypicalBuildingFromModel_Test#test_generic_gbxml:
NoMethodError: undefined method `each' for false:FalseClass
    :/ruby/2.7.0/gems/openstudio-standards-0.5.0/lib/openstudio-standards/standards/Standards.Model.rb:2218:in `model_differentiate_primary_secondary_thermal_zones'
    C:/Repos/NREL/ComStock/resources/measures/create_typical_building_from_model/resources/os_lib_model_generation.rb:3058:in `block (2 levels) in typical_building_from_model'
    C:/Repos/NREL/ComStock/resources/measures/create_typical_building_from_model/resources/os_lib_model_generation.rb:3055:in `each'
    C:/Repos/NREL/ComStock/resources/measures/create_typical_building_from_model/resources/os_lib_model_generation.rb:3055:in `block in typical_building_from_model'
    C:/Repos/NREL/ComStock/resources/measures/create_typical_building_from_model/resources/os_lib_model_generation.rb:3028:in `each'
    C:/Repos/NREL/ComStock/resources/measures/create_typical_building_from_model/resources/os_lib_model_generation.rb:3028:in `typical_building_from_model'
    C:/Repos/NREL/ComStock/resources/measures/create_typical_building_from_model/measure.rb:493:in `run'
    C:/Repos/NREL/ComStock/resources/measures/create_typical_building_from_model/tests/create_typical_building_from_model_test.rb:73:in `apply_measure_to_model'
    C:/Repos/NREL/ComStock/resources/measures/create_typical_building_from_model/tests/create_typical_building_from_model_test.rb:196:in `test_generic_gbxml'
```

-1 🍫

2024-03-12 15:19 UTC, eringold approved these changes

2024-03-12 15:21 UTC, merged