Ccaradon/euss timeseries plots
NatLabRockies/ComStock pull request #187
Opened 2024-06-20 21:27 UTC by ChristopherCaradonna

Pull request overview
---------------------

Adds the option to produce several timeseries plots comparing the baseline to upgrades. Plots include peak week by season, seasonal averages by day type, and seasonal averages by end use.

### Pull Request Author: Chris CaraDonna

This pull request makes changes to (select all the apply):
 - [ ] Documentation
 - [ ] Infrastructure (includes apptainer image, buildstock batch, dependencies, continuous integration tests)
 - [ ] Sampling
 - [ ] Workflow Measures
 - [ ] Upgrade Measures
 - [ ] Reporting Measures
 - [ ] Postprocessing

Author pull request checklist:

 - [ ] Tagged the pull request with the appropriate label (documentation, infrastructure, sampling, workflow measure, upgrade measure, reporting measure, postprocessing) to help categorize changes in the release notes.
 - [ ] Added tests for new measures
 - [ ] Updated measure .xml(s)
 - [ ] Register values added to `comstock_column_definitions.csv`
 - [ ] Both `options_lookup.tsv` files updated
 - [ ] 10k+ test run
 - [ ] Change documentation written
 - [ ] Measure documentation written
 - [ ] ComStock documentation updated
 - [ ] Changes reflected in example `.yml` files
 - [ ] Changes reflected in `README.md` files
 - [ ] Added 'See ComStock License' language to first two lines of each code file
 - [ ] Implements corresponding measure tests and indexing path in `test/measure_tests.txt` or/and `test/resource_measure_tests.txt`
 - [ ] All new and existing tests pass the CI

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a code review on GitHub
 - [ ] All related changes have been implemented: data and method additions, changes, tests
 - [ ] If fixing a defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] Reviewed change documentation
 - [ ] Ensured code files contain License reference
 - [ ] Results differences are reasonable
 - [ ] Make sure the newly added measures has been added with tests and indexed properly
 - [ ] CI status: all tests pass

#### ComStock Licensing Language - Add to Beginning of Each Code File
```
# ComStock™, Copyright (c) 2023 Alliance for Sustainable Energy, LLC. All rights reserved.
# See top level LICENSE.txt file for license terms.
```

2024-06-25 18:21 UTC, asparke2 requested changes
@ChristopherCaradonna looks good, 2 comments necessary to address, 1 that's optional (moving the color lists).

2024-06-25 18:21 UTC, asparke2 commented on postprocessing/compare_upgrades.py
> +#!/usr/bin/env python3
Should delete this file and just keep the .template version

2024-06-25 18:21 UTC, asparke2 commented on postprocessing/comstockpostproc/comstock_measure_comparison.py
> +        #self.plot_energy_by_enduse_and_fuel_type(df, column_for_grouping, color_map, output_dir)
Think these should not be commented out

2024-06-25 18:21 UTC, asparke2 commented on postprocessing/comstockpostproc/plotting_mixin.py
> +    order_list = [
There are 3 copies of this enduse list and corresponding color map in this file; is there a way to make this a Constant  that returns these things for reuse?

2024-07-03 16:07 UTC, rHorsey approved these changes
lgtm - thanks so much @ChristopherCaradonna

2024-07-03 16:07 UTC, merged