Rhorsey/sampling v2 plotting patch
NatLabRockies/ComStock pull request #217
Opened 2024-09-18 01:36 UTC by rHorsey

Pull request overview
---------------------

Updates plotting scripts for comparing upgrades, baselines, and CBECS. AMI and Timeseries are up next - EIA requires a transition to our current postproc paradigm.

 - Fixes #216 although I'm pretty sure the baseline there isn't correct, thus I've added a 10k sample to sampling/resources.

### Pull Request Author

This pull request makes changes to (select all the apply):
 - [ ] Documentation
 - [ ] Infrastructure (includes apptainer image, buildstock batch, dependencies, continuous integration tests)
 - [X] Sampling
 - [ ] Workflow Measures
 - [ ] Upgrade Measures
 - [ ] Reporting Measures
 - [X] Postprocessing

Author pull request checklist:

 - [X] Tagged the pull request with the appropriate label (documentation, infrastructure, sampling, workflow measure, upgrade measure, reporting measure, postprocessing) to help categorize changes in the release notes.
 - [ ] ~Added tests for new measures~
 - [ ] ~Updated measure .xml(s)~
 - [ ] ~Register values added to `comstock_column_definitions.csv`~
 - [ ] ~Both `options_lookup.tsv` files updated~
 - [X] 10k+ test run
 - [ ] ~Change documentation written~
 - [ ] ~Measure documentation written~
 - [ ] ~ComStock documentation updated~
 - [ ] ~Changes reflected in example `.yml` files~
 - [ ] ~Changes reflected in `README.md` files~
 - [X] Added 'See ComStock License' language to first two lines of each code file
 - [ ] ~Implements corresponding measure tests and indexing path in `test/measure_tests.txt` or/and `test/resource_measure_tests.txt`~
 - [ ] ~All new and existing tests pass the CI~

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a code review on GitHub
 - [ ] All related changes have been implemented: data and method additions, changes, tests
 - [ ] If fixing a defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] Reviewed change documentation
 - [ ] Ensured code files contain License reference
 - [ ] Results differences are reasonable
 - [ ] Make sure the newly added measures has been added with tests and indexed properly
 - [ ] CI status: all tests pass

#### ComStock Licensing Language - Add to Beginning of Each Code File
```
# ComStock™, Copyright (c) 2023 Alliance for Sustainable Energy, LLC. All rights reserved.
# See top level LICENSE.txt file for license terms.
```

2024-09-18 03:43 UTC, wnykuang commented
Looking

2024-09-18 22:29 UTC, wenyikuang commented on postprocessing/comstockpostproc/comstock.py
> +        if self.CBECS_WEIGHTS_APPLIED:
GREAT!

2024-09-18 22:30 UTC, wenyikuang commented on postprocessing/comstockpostproc/comstock.py
> +        if self.CBECS_WEIGHTS_APPLIED:
Actually there is a even shorter way:

assert self.CBECS_WEIGHTS_APPLIED == True , "Unable to apply apportionment weighting after CBECS weighting - reverse order."

2024-09-18 22:38 UTC, wenyikuang commented on postprocessing/comstockpostproc/comstock.py
> +        return lazyframe
`return lazyframe.rename(crnms)` will be exctaly same.

2024-09-18 22:57 UTC, wenyikuang approved these changes, later dismissed
Looks good, but I tried to run comstock_to_cbecs_comparison.py with the default template but not works due to `eulp/euss_com/cycle_4_sampling_test_rand_985932_20240321/cycle_4_sampling_test_rand_985932_20240321/` is not existed, the right path should be `cycle_4_sampling_test_rand_985932_20240321/rand_985932_20240321/baseline/`

2024-09-19 20:59 UTC, rHorsey commented
Thanks @wenyikuang - updated the paths and also switched to using Resource instead of Client in boto3 to avoid an error with the policy on stuff uploaded from Kestrel using the default upload policy.

2024-09-19 21:00 UTC, rHorsey commented
@ChristopherCaradonna  can you delete the lighting upgrade in you comstock_data and try rerunning compare_upgrades again? If that works as expected can you review / approve please?

2024-09-19 21:37 UTC, ChristopherCaradonna requested changes
@rHorsey Postprocessing completed, most plots look good.

2 Issues:
1) Census Division plots show no energy / square footage in "Middle Atlantic".
2) Non-breaking error message, as show below
Bonus) I get an error for not having 'import json' in the s3_utilties_mixin.py

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\ccaradon\AppData\Local\anaconda3\envs\comstockpostproc\lib\logging\__init__.py", line 1083, in emit
    msg = self.format(record)
  File "C:\Users\ccaradon\AppData\Local\anaconda3\envs\comstockpostproc\lib\logging\__init__.py", line 927, in format
    return fmt.format(record)
  File "C:\Users\ccaradon\AppData\Local\anaconda3\envs\comstockpostproc\lib\logging\__init__.py", line 663, in format
    record.message = record.getMessage()
  File "C:\Users\ccaradon\AppData\Local\anaconda3\envs\comstockpostproc\lib\logging\__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\ccaradon\Documents\GitHub\ComStock\postprocessing\compare_upgrades.py", line 73, in <module>
    main()
  File "C:\Users\ccaradon\Documents\GitHub\ComStock\postprocessing\compare_upgrades.py", line 58, in main
    comstock.add_national_scaling_weights(cbecs, remove_non_comstock_bldg_types_from_cbecs=True)
  File "C:\Users\ccaradon\Documents\GitHub\ComStock\postprocessing\comstockpostproc\comstock.py", line 1900, in add_national_scaling_weights
    logger.info("sf wt_area_col shape: ", sf[wt_area_col].shape)
Message: 'sf wt_area_col shape: '
Arguments: ((14,),)

2024-09-19 21:37 UTC, ChristopherCaradonna commented on postprocessing/compare_upgrades.py.template
> +    # comstock.export_to_csv_long()  # Long format useful for stacking end uses and fuels
Where is ComStock wide export?

2024-09-19 22:26 UTC, rHorsey commented on postprocessing/compare_upgrades.py.template
> +    # comstock.export_to_csv_long()  # Long format useful for stacking end uses and fuels
That's the create_national_aggregations method now - same code under the hood but redone to get correctly weighted national level results!

2024-09-19 22:26 UTC, rHorsey commented
@ChristopherCaradonna 's issues addressed - ready for approval! Great catch on mid-atlantic - many thanks!.

2024-09-23 14:23 UTC, ChristopherCaradonna approved these changes
Changes look good, approved.

2024-09-23 18:05 UTC, merged