Os 370 update
NatLabRockies/ComStock pull request #43
Opened 2023-11-30 19:43 UTC by mpraprost

Pull request overview
---------------------

Updating ComStock from OS 3.6.1 to 3.7.0
- Gemfile and Dockerfile updated with new versions
- DistrictHeating fuel enum changed to DistrictHeatingWater
- Change documentation located here: https://nrel.sharepoint.com/:w:/r/sites/comstock/Shared%20Documents/ComStock%20Filing%20Cabinet/Change%20Documentation/Changes/v23%20OpenStudio%203.6.1%20to%203.7.0%20Update/ComStock%20Update%20OS%203.7.0%20Version%20Change.docx?d=wbbd9b94aacba4f7e92b4d9ca241b5e8e&csf=1&web=1&e=fgtt7e

 - Fixes #ISSUENUMBERHERE (IF RELEVANT)

### Pull Request Author: Marley Praprost

This pull request makes changes to (select all the apply):
 - [ ] Documentation
 - [X] Infrastructure (includes singularity image, buildstock batch, dependencies, continuous integration tests)
 - [ ] Sampling
 - [X] Workflow Measures
 - [ ] Upgrade Measures
 - [X] Reporting Measures
 - [ ] Postprocessing

Author pull request checklist:

 - [X] Tagged the pull request with the appropriate label (documentation, infrastructure, sampling, workflow measure, upgrade measure, reporting measure, postprocessing) to help categorize changes in the release notes.
 - [ ] Added tests for new measures
 - [ ] Updated measure .xml(s)
 - [ ] Register values added to `comstock_column_definitions.csv`
 - [ ] Both `options_lookup.tsv` files updated
 - [X] 10k+ test run
 - [X] Change documentation written
 - [ ] Measure documentation written
 - [ ] ComStock documentation updated
 - [ ] Changes reflected in example `.yml` files
 - [ ] Changes reflected in `README.md` files
 - [ ] Added 'See ComStock License' language to first two lines of each code file
 - [ ] All new and existing tests pass the CI

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a code review on GitHub
 - [ ] All related changes have been implemented: data and method additions, changes, tests
 - [ ] If fixing a defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] Reviewed change documentation
 - [ ] Ensured code files contain License reference
 - [ ] Results differences are reasonable
 - [ ] CI status: all tests pass

#### ComStock Licensing Language - Add to Beginning of Each Code File
```
# ComStock™, Copyright (c) 2023 Alliance for Sustainable Energy, LLC. All rights reserved.
# See top level LICENSE.txt file for license terms.
```

2023-12-01 19:17 UTC, asparke2 requested changes
The results in the change doc look good. A few minor code changes below, mostly related to backwards compatibility code.

2023-12-01 19:17 UTC, asparke2 commented on resources/measures/set_heating_fuel/measure.rb
> +      eplus_htg_fuels['DistrictHeating'] = 'DistrictHeatingWater'
I think this is incorrect. This change is inside an `if` statement for backwards compatibility, so instead of listing the NEW enumeration here, you need to list the old enumeration. On line 108, you're setting the default for the current OS version (370), which is now `DistrictHeatingWater`. So then you need a new backwards-compatibility switch for OS versions < 370 to change back to `DistrictHeating`, like this (not tested): 

```ruby
    # Compatibility with earlier EnergyPlus versions with
    # inconsistent fuel enumerations between objects.
    if model.version < OpenStudio::VersionString.new('3.0.0')
      eplus_htg_fuels['FuelOil'] = 'FuelOil#2'
    end
    if model.version < OpenStudio::VersionString.new('3.7.0')
      eplus_htg_fuels['DistrictHeating'] = 'DistrictHeating'
    end
```

2023-12-01 19:17 UTC, asparke2 commented on resources/measures/set_service_water_heating_fuel/measure.rb
> +        'DistrictHeating' => 'DistrictHeatingWater'
I think you need a new backwards-compatibility switch on line ~112 here too: 
```ruby
    if model.version < OpenStudio::VersionString.new('3.7.0')
      eplus_htg_fuels['DistrictHeating'] = 'DistrictHeating'
    end
```

2023-12-01 19:17 UTC, asparke2 commented on resources/measures/upgrade_hvac_vrf_hr_doas/measure.rb
>        htg_fuels = thermalzone.heating_fuels
pretty sure you need to change:
`htg_fuels = thermalzone.heating_fuels`
to:
`htg_fuels = thermalzone.heatingFuelTypes.map(&:valueName)`

because the `ThermalZone.heating_fuels()` method was removed from Ruby in OpenStudio-Standards and put into OS C++ code.  I think this actually happened in 3.6.1 and probably was an oversight then.

2023-12-04 15:57 UTC, asparke2 approved these changes

2023-12-04 16:06 UTC, ChristopherCaradonna approved these changes

2023-12-04 16:06 UTC, merged