Add AMI comparisons to postprocessing
NatLabRockies/ComStock pull request #52
Opened 2023-12-12 21:57 UTC by mdahlhausen

Pull request overview
---------------------

This PR adds AMI data comparisons from EULP to the postprocessing workflow. The AMI data is available on AWS in an Athena table.

This includes:
- methods to download and process timeseries AMI data
- methods to download and process timeseries ComStock data
- adds an `ami_comparison.csv` to create a 10k `buildstock.csv` sample to compare against the AMI regions
- adds plotting for stacked end use plots by season and day type, either by kwh per sf, or annual or daytype normalizations
- adds plotting for load duration curves
- adds a test

### Pull Request Author

This pull request makes changes to (select all the apply):
 - [x] Postprocessing

Author pull request checklist:
 - [x] Tagged the pull request with the appropriate label (documentation, infrastructure, sampling, workflow measure, upgrade measure, reporting measure, postprocessing) to help categorize changes in the release notes.
 - [x] Added tests for postprocessing
 - [x] 10k+ test run
 - [ ] ComStock documentation updated
 - [ ] Changes reflected in `README.md` files
 - [x] Added 'See ComStock License' language to first two lines of each code file
 - [ ] All new and existing tests pass the CI

### Specific Review Requests
- What, if any content should I add to the postprocessing README?
- Should some of AMI comparisons be included in the release or documentation? Perhaps a separate calibration report to accompany the reference documentation?
- I don't often write in python, so my syntax may be messy. code review it please.
- What other plots should I include?

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a code review on GitHub
 - [ ] All related changes have been implemented: data and method additions, changes, tests
 - [ ] If fixing a defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] Reviewed change documentation
 - [ ] Ensured code files contain License reference
 - [ ] Results differences are reasonable
 - [ ] CI status: all tests pass

2023-12-12 22:01 UTC, mdahlhausen commented
There are some messy warning about enumerations when I run the test. Those seem to come from other parts of the code. Perhaps worth making a github issue if you can track it down.

2024-01-08 22:06 UTC, eringold approved these changes, later dismissed
Plots generate when downloading or reloading data. Looks good!

2024-01-08 22:06 UTC, eringold commented on postprocessing/compare_comstock_to_ami.py
Adding ability to run as a script, simliar to other 'compare_comstock_to' scripts

2024-01-08 22:06 UTC, eringold commented on postprocessing/comstockpostproc/ami.py
> +            self.ami_timeseries_data = pd.read_csv(file_path, low_memory=False, index_col='timestamp', parse_dates=True)
needed to set index col and dtype when loading from csv

2024-01-08 22:06 UTC, eringold commented on postprocessing/comstockpostproc/ami.py
> +                df = pd.read_csv(file_path, parse_dates=['timestamp'], index_col='timestamp')
index col and dtype set when not reloading from csv

2024-01-08 22:06 UTC, eringold commented on postprocessing/comstockpostproc/comstock.py
> +            self.ami_timeseries_data = pd.read_csv(file_path, low_memory=False, index_col='timestamp', parse_dates=True)
set index col and dtype when loading from csv

2024-01-08 22:06 UTC, eringold commented on postprocessing/comstockpostproc/comstock.py
> +        agg_df['timestamp'] = agg_df.apply(
timestamp col as datetime

2024-01-08 22:06 UTC, eringold commented on postprocessing/comstockpostproc/comstock.py
> +        ).set_index('timestamp')
timestamp as index

2024-01-08 22:10 UTC, eringold commented
@mdahlhausen Please see if everything still works on your end. If so, I think it's good to merge.

2024-01-09 03:46 UTC, asparke2 requested changes
**What, if any content should I add to the postprocessing README?**
For the README, write a little section like [this](https://github.com/NREL/ComStock/blob/ami_comparisons/postprocessing/README.md#comparing-one-or-more-comstock-runs-to-each-other-and-cbecs) that explains how to do an AMI comparison. @eringold committed a template script already, so just describe how to use it.

**Existing Plots and Code**
The plots now work for me as well.  Some of them have a slightly clipped peak (see example below), but I don't know that it's important enough to bother fixing unless it's something quick. Otherwise I think the code is fine.

![image](https://github.com/NREL/ComStock/assets/2009290/e95dfdf7-0d7b-49ef-95fe-4587ea53c86f)

**Other Plots**
Two other plots that could be useful:
1. A comparison of all the AMI for each building type plotted on one plot. Could do it normalized and absolute. Basically to give people an understanding of how similar/not the AMI is from region to region.
2. The plot that showed an example week of data for both AMI and ComStock. Sometimes it's easier to pick out things like a time shift when you can see the whole week at once.

**Where to Release Comparisons**
I think we'd like to release the comparisons with the next EUSS release. The first version might just be a folder with a bunch of images on OEDI. We could also try to make a LaTeX template document that just has the hard-coded paths in it and generate a PDF with just a bunch of figures and little/no discussion.

2024-01-09 20:43 UTC, mdahlhausen commented
Thanks @eringold and @asparke2.

I'll address two items before merging:
- Adding README content
- The clipped y-axis on some plots

I've been working on summary graphic and statistics that we can use in reports and to guide calibration at a high level. I'll add those in a follow-up PR, along with the two other requested graphs (a plot comparing AMI data, week realizations).

2024-01-10 21:56 UTC, mdahlhausen commented
@asparke2:
- reran comparison script from new install of comstock repo and new environment
- added missing truth data
- cast dtypes for polars dataframes
- added README content
- fixed y max issue on day normalized plots
- fixed CBECS comparison test

Should be good to merge now.

I will add the week realizations and a summary of AMI comparisons for the documentation in a future PR

2024-01-11 13:37 UTC, asparke2 approved these changes

2024-01-11 13:37 UTC, merged