Add soil properties as additional properties
NatLabRockies/ComStock pull request #63
Opened 2023-12-22 19:18 UTC by mpraprost

Pull request overview
---------------------

Adds soil conductivity as sampled field in baseline. Change building location measure adds soil conductivity and undisturbed ground temperature as additional properties to the building. These are not used unless the geothermal heat pump upgrade measures are run. Does not affect baseline, no change documentation required. 

 - Fixes #ISSUENUMBERHERE (IF RELEVANT)

### Pull Request Author

This pull request makes changes to (select all the apply):
 - [ ] Documentation
 - [ ] Infrastructure (includes singularity image, buildstock batch, dependencies, continuous integration tests)
 - [ ] Sampling
 - [X] Workflow Measures
 - [ ] Upgrade Measures
 - [ ] Reporting Measures
 - [ ] Postprocessing

Author pull request checklist:

 - [X] Tagged the pull request with the appropriate label (documentation, infrastructure, sampling, workflow measure, upgrade measure, reporting measure, postprocessing) to help categorize changes in the release notes.
 - [ ] Added tests for new measures
 - [ ] Updated measure .xml(s)
 - [ ] Register values added to `comstock_column_definitions.csv`
 - [X] Both `options_lookup.tsv` files updated
 - [X] 10k+ test run
 - [ ] Change documentation written
 - [ ] Measure documentation written
 - [ ] ComStock documentation updated
 - [ ] Changes reflected in example `.yml` files
 - [ ] Changes reflected in `README.md` files
 - [ ] Added 'See ComStock License' language to first two lines of each code file
 - [ ] All new and existing tests pass the CI

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a code review on GitHub
 - [ ] All related changes have been implemented: data and method additions, changes, tests
 - [ ] If fixing a defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] Reviewed change documentation
 - [ ] Ensured code files contain License reference
 - [ ] Results differences are reasonable
 - [ ] CI status: all tests pass

#### ComStock Licensing Language - Add to Beginning of Each Code File
```
# ComStock™, Copyright (c) 2023 Alliance for Sustainable Energy, LLC. All rights reserved.
# See top level LICENSE.txt file for license terms.
```

2024-01-02 16:42 UTC, mdahlhausen commented on sampling/tsvs/tsvs-v23.zip
This file is causing errors. I can unzip v22, but not v23.

2024-01-02 16:43 UTC, mdahlhausen commented on sampling/tsv_resampling.py
> +                'cook', 'ground_thermal_conductivity'
can this variable be placed with other location variables (climate_zone, region, state, county, etc.? same for the other sampling file.

2024-01-02 16:44 UTC, mdahlhausen commented on resources/measures/ChangeBuildingLocation/measure.rb
> +    puts "climate zone = #{climate_zone}"
no puts statements in measures

2024-01-02 16:45 UTC, mdahlhausen commented on resources/measures/ChangeBuildingLocation/measure.rb
> +    undisturbed_ground_temps = {
move this to the measure resources directory, and organize by institution. Ordering by ground temp is confusing.

2024-01-02 16:47 UTC, mdahlhausen commented on resources/measures/ChangeBuildingLocation/measure.rb
> +    return true
adding return true here misses the final register at end of measure. remove.

2024-01-02 16:49 UTC, mdahlhausen requested changes
See comments above. The measure needs changes in the measure.rb, and the tsv v23 zip needs to be regenerated.

Also, please add tests to the changebuildinglocation measure tests for soil conductivity.

2024-01-02 16:49 UTC, mdahlhausen commented on resources/measures/ChangeBuildingLocation/measure.rb
> +    soil_conductivity.setDefaultValue(1.5) # Default value, change as needed
comment is redundant; delete

2024-01-02 16:50 UTC, mdahlhausen commented on resources/measures/ChangeBuildingLocation/measure.xml
regenerate .xml after changes

2024-01-02 18:10 UTC, mpraprost commented
@mdahlhausen please review the changes. the soil properties measure test works but the rest are broken. those may need to get fixed within another PR

2024-01-03 16:04 UTC, mdahlhausen commented
@mpraprost I made a few changes to the measure so the tests would run. Now there is a new error in some of the tests where the undisturbed ground temperature lookup is failing to find a match to the climate zone. You'll need to add more error checking, and will need to lookup the climate zone from the model instead of using the measure argument which has 'lookup from stat file' as the default.

2024-01-11 02:31 UTC, mdahlhausen approved these changes

2024-01-11 02:31 UTC, merged